<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Massini.Graphics.VkAL\Massini.Graphics.VkAL.csproj" />
    <ProjectReference Include="..\Massini.Math\Massini.Math.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.SPIRV.Reflect" Version="2.23.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
