<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <RootNamespace>Atomic.runtime.linux_x64.vma</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\Native\Binaries\linux-x64\libVmaExporter.so" Pack="true">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <RelativeRuntimePath>runtimes/linux-x64/native/libVmaExporter.so</RelativeRuntimePath>

            <PackagePath>%(RelativeRuntimePath)</PackagePath>
            <TargetPath>%(RelativeRuntimePath)</TargetPath>
        </None>
    </ItemGroup>
    
</Project>
