namespace Massini.Bindings.Vulkan
{
    [NativeTypeName("unsigned int")]
    public enum VkRayTracingInvocationReorderModeEXT : uint
    {
        VK_RAY_TRACING_INVOCATION_REORDER_MODE_NONE_EXT = 0,
        VK_RAY_TRACING_INVOCATION_REORDER_MODE_REORDER_EXT = 1,
        VK_RAY_TRACING_INVOCATION_REORDER_MODE_NONE_NV = VK_RAY_TRACING_INVOCATION_REORDER_MODE_NONE_EXT,
        VK_RAY_TRACING_INVOCATION_REORDER_MODE_REORDER_NV = VK_RAY_TRACING_INVOCATION_REORDER_MODE_REORDER_EXT,
        VK_RAY_TRACING_INVOCATION_REORDER_MODE_MAX_ENUM_EXT = 0x7FFFFFFF,
    }
}
