<Project>
	<PropertyGroup>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

		<PackageOutputPath>$(MSBuildThisFileDirectory)..\nuget\</PackageOutputPath>

		<!-- Generate documentation [.xml] files. -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<!-- Copy dependencies to output. -->
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)THIRDPARTY_NOTICES.md" 
			Pack="true" 
			PackagePath="\" 
			Visible="true" />
  	</ItemGroup>

	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
</Project>